IGI/LR5/LabRab5_IGI/LabRab5_IGI/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('onlineshop/', include('onlineshop.urls')),
]

# Добавьте URL соотношения, чтобы перенаправить запросы с корневого URL, на URL приложения
from django.views.generic import RedirectView

urlpatterns += [
    path('', RedirectView.as_view(url='/onlineshop/', permanent=True)),
]

# Используйте static() чтобы добавить соотношения для статических файлов
# Только на период разработки
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]
# from django.contrib.auth.views import LogoutView
# from django.urls import path
#
# class LogoutViewWithGet(LogoutView):
#     def get(self, request):
#         return self.post(request)
#
# urlpatterns += [
#     path('accounts/logout/', LogoutViewWithGet.as_view(), name='logout'),
# ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IGI/LR5/LabRab5_IGI/onlineshop/urls.py
from . import views
from django.conf import settings
from django.urls import re_path
from django.conf.urls.static import static


urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^products/$', views.ProductListView.as_view(), name='products'),
    re_path(r'^product/(?P<pk>\d+)$', views.ProductDetailView.as_view(), name='product-detail'),
    re_path(r'^manufacturers/$', views.ManufacturerListView.as_view(), name='manufacturers'),
    re_path(r'^manufacturers/(?P<pk>\d+)$', views.ManufacturerDetailView.as_view(), name='manufacturer-detail'),
    re_path(r'^contacts/$', views.Contacts_view, name='contacts'),
    re_path(r'^vacation/$', views.Vacation_view, name='vacation'),
    re_path(r'^reviews/$', views.reviews_list, name='reviews'),
    re_path(r'^privacy_policy/$', views.privacy_policy, name='privacy_policy'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^order_list/$', views.OrderListView.as_view(), name='order_list'),
    re_path(r'^pickup_points/$', views.PickupPointListView.as_view(), name='pickup_points'),
    re_path(r'^orders/$', views.FullOrderListView.as_view(), name='orders'),
    re_path(r'^orders/(?P<order_id>\d+)/edit/$', views.edit_order, name='edit_order'),
    re_path(r'^orders/(?P<order_id>\d+)/delete/$', views.delete_order, name='delete_order'),
    re_path(r'^orders/mark-as-completed/(?P<order_id>\d+)/$', views.mark_as_completed, name='mark_as_completed'),
    re_path(r'^sales/$', views.sales_list, name='sales'),
    re_path(r'^sales_by_hour/$', views.sales_by_hour, name='sales_by_hour'),
    re_path(r'^news/$', views.news_list, name='news_list'),
    re_path(r'^reviews/$', views.review_list, name='review_list'),
    re_path(r'^reviews/add/$', views.add_review, name='add_review'),
    re_path(r'^faq/$', views.faq_list, name='faq_list'),
    re_path(r'^faq/add/$', views.add_faq, name='add_faq'),
    re_path(r'^user_sales/$', views.user_sales, name='user_sales'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^coupons/$', views.coupon_list, name='coupon_list'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IGI/LR5/LabRab5_IGI/onlineshop/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.conf import settings

import sys
from django.contrib.auth.models import User, AbstractUser, Group, Permission

sys.path.append('/Users/andreitsyrkunov/Desktop/labigidjango/LabRab5_IGI/.venv/Lib/site-packages')


class ProductType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('manufacturer-detail', args=[str(self.id)])


class UnitOfMeasure(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE)
    manufacturer = models.ForeignKey("Manufacturer", on_delete=models.CASCADE, null=True)
    unit_of_measure = models.ForeignKey(UnitOfMeasure, on_delete=models.SET_NULL, null=True)

    # image = models.ImageField(upload_to='products/', null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])



class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    product_name = models.CharField(max_length=200)
    product_price = models.DecimalField(max_digits=10, decimal_places=2)
    is_completed = models.BooleanField(default=False)
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255)

    def __str__(self):
        return f"Заказ {self.id} пользователя {self.user} на продукт {self.product_name}"


class Sale(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sale_date = models.DateTimeField(auto_now_add=True)
    product_name = models.CharField(max_length=200)
    product_price = models.DecimalField(max_digits=10, decimal_places=2)
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255)

    def __str__(self):
        return f"Продажа {self.id} пользователю {self.user} продукта {self.product_name}"


class PickupPoint(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    latitude = models.FloatField()
    longitude = models.FloatField()
    work_hours = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Vacation(models.Model):
    title = models.CharField('Название', max_length=100)
    description = models.TextField('Описание')
    salary = models.IntegerField('Зарплата')

    def __str__(self):
        return self.title


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=5)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    discount_percent = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class NewsArticle(models.Model):
    title = models.CharField(max_length=200)
    summary = models.TextField()
    image = models.ImageField(upload_to='news_images/')
    publication_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class FAQ(models.Model):
    question = models.CharField(max_length=255)
    answer = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question


class ClientData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    date_birthday = models.DateTimeField(max_length=255)

    def __str__(self):
        return self.phone_number

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/about.html
{% extends 'base_generic.html' %}

{% block title %}About Us{% endblock %}

{% block content %}
<h1>О нашей компании</h1>

<p>Наш онлайн-магазин доставки был основан в 2020 году с целью предоставить нашим клиентам удобный и надежный способ получения товаров. Мы специализируемся на доставке широкого ассортимента продуктов, товаров для дома и других повседневных необходимостей прямо к вашей двери.</p>

<p>Наша команда состоит из опытных специалистов в области логистики и электронной коммерции, которые работают круглосуточно, чтобы гарантировать быструю и качественную доставку ваших заказов.</p>

<p>Мы гордимся нашей приверженностью к отличному обслуживанию клиентов и стремимся предоставлять надежные и удобные решения для всех ваших потребностей в доставке. Благодарим вас за выбор нашего онлайн-магазина!</p>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/add_faq.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="container">
    <h1>Добавить новый вопрос</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="question">Вопрос</label>
            <input type="text" class="form-control" id="question" name="question" required>
        </div>
        <div class="form-group">
            <label for="answer">Ответ</label>
            <textarea class="form-control" id="answer" name="answer" rows="4" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Отправить</button>
    </form>
</div>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/faq_list.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="container">
    <h1>Часто задаваемые вопросы</h1>
    <div class="mt-4">
        {% for faq in faqs %}
        <div class="card mb-4">
            <div class="card-body">
                <h5 class="card-title">{{ faq.question }}</h5>
                <p class="card-text">{{ faq.answer }}</p>
                <p class="card-text"><small class="text-muted">Добавлено {{ faq.date_added|date:"d M Y" }}</small></p>
            </div>
        </div>
        {% endfor %}
    </div>

    {% if user.is_superuser or user.is_staff %}
    <a href="{% url 'add_faq' %}" class="btn btn-primary">Добавить новый вопрос</a>
    {% endif %}
</div>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/manufacturer_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Компания: {{ manufacturer.name }}</h1>

  <p><strong>Описание:</strong> {{ manufacturer.description }}</p>
  <p><strong>Местоположение:</strong> {{ manufacturer.location }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Продукты</h4>

    {% for product in manufacturer.product_set.all %}
    <hr>
    <p><strong>Название продукта:</strong> <a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
    <p><strong>Цена:</strong> {{ product.price }}</p>
    <p class="text-muted"><strong>Id:</strong> {{ product.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/manufacturer_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список производителей</h1>

    {% if manufacturer_list %}
    <ul>

      {% for manufacturer in manufacturer_list %}
      <li>
        <a href="{{ manufacturer.get_absolute_url }}">{{ manufacturer.name }}</a> ({{ manufacturer.phone }})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no manufacturers in the online-shop.</p>
    {% endif %}
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/news_list.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Новости</h1>
<div class="news-list">
    {% for article in articles %}
    <div class="news-article">
        <h2>{{ article.title }}</h2>
        <p>{{ article.summary }}</p>
        <img src="{{ article.image.url }}" alt="{{ article.title }}">
        <p><small>Опубликовано: {{ article.publication_date }}</small></p>
    </div>
    {% endfor %}
</div>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/order_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Ваши заказы</h1>

  {% if orders %}
    <ul>
      {% for order in orders %}
        <li>
          Заказ #{{ order.id }} от {{ order.order_date }}
          <ul>
            {% for product in order.products.all %}
              <li>{{ product.name }} - {{ product.price }}</li>
            {% endfor %}
          </ul>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>У вас пока нет заказов.</p>
  {% endif %}
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/orders.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Все заказы</h1>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Пользователь</th>
            <th>Дата заказа</th>
            <th>Тип продукта</th>
            <th>Цена</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Телефон</th>
            <th>Адрес</th>
            <th>Действие</th>
        </tr>
    </thead>
    <tbody>
        {% for order in orders %}
        <tr>
            <form method="POST" action="{% url 'edit_order' order.id %}">
                {% csrf_token %}
                <td>{{ order.id }}</td>
                <td>{{ order.user }}</td>
                <td>{{ order.order_date }}</td>
                <td>{{ order.product_name }}</td>
                <td>{{ order.product_price }}</td>
                <td><input type="text" name="name" value="{{ order.name }}"></td>
                <td><input type="text" name="surname" value="{{ order.surname }}"></td>
                <td><input type="text" name="phone" value="{{ order.phone }}"></td>
                <td><input type="text" name="address" value="{{ order.address }}"></td>
                <td>
                    {% if not order.is_completed %}
                    <a href="{% url 'mark_as_completed' order.id %}" class="btn btn-primary">Отметить как выполненный</a>
                    {% else %}
                    <span class="text-success">Выполнено</span>
                    {% endif %}
                    <button type="submit" class="btn btn-secondary">Сохранить</button>
                    <a href="{% url 'delete_order' order.id %}" class="btn btn-danger">Удалить</a>
                </td>
            </form>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/privacy_policy.html
{% extends 'base_generic.html' %}


{% block content %}
<h1>Политика конфиденциальности</h1>

<p>Это заглушка для страницы Политики конфиденциальности. Фактический контент будет добавлен позже..</p>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/product_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Название продукта: {{ product.name }}</h1>
<p><strong>Описание:</strong> {{ product.description }}</p>
<p><strong>Цена:</strong> {{ product.price }}</p>
<p><strong>Тип продукта:</strong> {{ product.product_type }}</p>
<p><strong>Количество:</strong> {{ product.unit_of_measure }}</p>
<p><strong>Производитель:</strong> <a href="">{{ product.manufacturer }}</a></p>

{% if user.is_authenticated %}

  {% if phone_error %}
  <div class="alert alert-danger">{{ phone_error }}</div>
  {% endif %}

  {% if email_error %}
  <div class="alert alert-danger">{{ email_error }}</div>
  {% endif %}

  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="product_name" value="{{ product.name }}">
    <input type="hidden" name="product_price" value="{{ product.price }}">

    <div class="form-group">
      <label for="name">Имя</label>
      <input type="text" class="form-control" id="name" name="name" value="{{ user.first_name }}" required>
    </div>

    <div class="form-group">
      <label for="surname">Фамилия</label>
      <input type="text" class="form-control" id="surname" name="surname" value="{{ user.last_name }}" required>
    </div>

    <div class="form-group">
      <label for="phone">Телефон</label>
      <input type="tel" class="form-control" id="phone" name="phone" value="{{ user.clientdata.phone_number }}" required>
    </div>

    <div class="form-group">
      <label for="email">Электронная почта</label>
      <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}" required>
    </div>

    <div class="form-group">
      <label for="address">Адрес</label>
      <input type="text" class="form-control" id="address" name="address" value="{{ user.clientdata.address }}" required>
    </div>

    <div class="form-group">
      <label for="coupon">Промокод (необязательно)</label>
      <input type="text" class="form-control" id="coupon" name="coupon">
    </div>

    <button type="submit" class="btn btn-primary">Разместить заказ</button>
  </form>

{% endif %}

{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/reviews.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="container">
    <h1>Отзывы</h1>

    {% if reviews %}
    <div class="row">
        {% for review in reviews %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ review.user.username }}</h5>
                    <p class="card-text">
                        {% for i in ""|ljust:review.rating %}
                        ★
                        {% endfor %}
                        - {{ review.text }}
                    </p>
                    <p class="card-text"><small class="text-muted">Оставлено {{ review.created_at|timesince }} назад</small></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>Пока нет отзывов.</p>
    {% endif %}

    {% if user.is_authenticated %}
    <div class="mt-4">
        <h2>Добавить отзыв</h2>
        <form method="POST" action="{% url 'add_review' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="rating">Оценка</label>
                <select id="rating" name="rating" class="form-control">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="text">Отзыв</label>
                <textarea id="text" name="text" class="form-control" rows="4"></textarea>
            </div>
            <button type="submit" class="btn btn-primary mt-2">Отправить</button>
        </form>
    </div>
    {% else %}
    <p>Пожалуйста, <a href="{% url 'login' %}">войдите</a>
    {% endif %}
</div>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/sales_by_hour.html
{% extends 'base_generic.html' %}

{% load static %}


{% block content %}
<h1>Продажи по часам</h1>

<p>Ниже представлен график количества продаж по часам:</p>

<img src="{% static 'sales_by_hour2.png' %}" alt="Продажи по часам">

{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/user_sales.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Ваши покупки</h1>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Дата продажи</th>
            <th>Тип продукта</th>
            <th>Цена</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Телефон</th>
            <th>Адрес</th>
        </tr>
    </thead>
    <tbody>
        {% for sale in user_sales %}
        <tr>
            <td>{{ sale.id }}</td>
            <td>{{ sale.sale_date }}</td>
            <td>{{ sale.product_name }}</td>
            <td>{{ sale.product_price }}</td>
            <td>{{ sale.name }}</td>
            <td>{{ sale.surname }}</td>
            <td>{{ sale.phone }}</td>
            <td>{{ sale.address }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/vacation.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Вакансии</h1>

<div class="row">
  {% for vacation in vacations %}
  <div class="col-md-4 mb-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ vacation.title }}</h5>
        <p class="card-text">{{ vacation.description }}</p>
        <p class="card-text">Зарплата: {{ vacation.salary }} руб.</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}